[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts"]
ffi = true # it will foundry to execute script on system

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
